# Ruby CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/ruby/ for more details
#
version: 2.1


orbs:
  ruby: circleci/ruby@0.1.2 # Ruby orb registry: https://circleci.com/orbs/registry/orb/circleci/ruby

machine:
  environment:
    TESTOPTS: "--ci-dir=$CIRCLE_TEST_REPORTS/reports"

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run:
          name: Parallel Minitest
          command: bundle exec rake test
      - store_test_results:
          path: results

test:
  override:
    - bundle exec rake test:
        parallel: true
        files:
          - test/**/*.rb

# What to do next? Set up a test job. Please see
# https://circleci.com/docs/2.0/configuration-reference/, for more  info on how to get started.
